# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-24 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Historico',
            },
        ),
        migrations.CreateModel(
            name='modo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Modos',
            },
        ),
        migrations.CreateModel(
            name='planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_planta', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Plantas',
            },
        ),
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sensor', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=200)),
                ('tb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tn', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('planta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clima.planta')),
            ],
            options={
                'verbose_name_plural': 'Sensores',
            },
        ),
        migrations.CreateModel(
            name='tipo_sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_sensor', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipos_Sensores',
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='tipo_sensor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clima.tipo_sensor'),
        ),
        migrations.AddField(
            model_name='historico',
            name='sensor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clima.sensor'),
        ),
        migrations.AddField(
            model_name='calendario',
            name='modo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clima.modo'),
        ),
        migrations.AddField(
            model_name='calendario',
            name='sensor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clima.sensor'),
        ),
    ]
