# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-29 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0002_auto_20181029_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendario',
            options={'verbose_name_plural': 'Calendario'},
        ),
    ]
