# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-29 20:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0006_auto_20181029_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendario',
            old_name='nombre_sensor',
            new_name='sensor',
        ),
        migrations.AlterField(
            model_name='calendario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
