# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0007_auto_20181029_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='ultima_temperatura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
