# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0008_sensor_ultima_temperatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='sensor_instalacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sensor', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clima.estado')),
                ('tipo_sensor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clima.tipo_sensor')),
            ],
            options={
                'verbose_name_plural': 'Sensores instalaci\xf3n',
            },
        ),
    ]
