# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0009_estado_sensor_instalacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='codigo',
            field=models.IntegerField(default=0),
        ),
    ]
