# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0011_auto_20181107_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor_instalacion',
            name='puerto',
            field=models.IntegerField(default=0),
        ),
    ]
