# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 11:10
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0012_sensor_instalacion_puerto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='bateria',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='historico',
            name='humedad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='sensor',
            name='bateria',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='sensor',
            name='humedad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
