# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0013_auto_20181115_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='lectura',
            field=models.BooleanField(default=True),
        ),
    ]
